-- 캐시 충전 상품(패키지) 테이블 (07-22 웹상점 개편).
--  원화로 결제해 캐시를 충전하는 프리셋 상품. 본문 상세 소개는 site_settings 로 공통 관리.
CREATE TABLE public.cash_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    price_krw bigint NOT NULL,
    cash_amount bigint NOT NULL,
    icon_url varchar(500),
    sort_order integer NOT NULL DEFAULT 0,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE INDEX idx_cash_products_active_sort ON public.cash_products (active, sort_order);
