-- V1 baseline: Hibernate(ddl-auto=create)가 생성한 스키마의 pg_dump 스냅샷 (2026-07-05).
-- 기존 DB는 baseline-on-migrate 로 이 버전을 건너뛰고, 새 DB에만 적용된다.

CREATE TABLE public.admin_users (
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    last_login_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    role character varying(30) NOT NULL,
    username character varying(80) NOT NULL,
    password_hash character varying(120) NOT NULL,
    CONSTRAINT admin_users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'OPERATOR'::character varying, 'SUPER_ADMIN'::character varying])::text[])))
);

ALTER TABLE public.admin_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.audit_logs (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    action character varying(80) NOT NULL,
    entity_type character varying(80) NOT NULL,
    actor character varying(120) NOT NULL,
    entity_id character varying(120) NOT NULL,
    new_value oid,
    old_value oid
);

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.cash_balances (
    balance bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.cash_balances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cash_balances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.cash_charges (
    cash_amount bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    paid_at timestamp(6) with time zone,
    payment_amount_krw bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    status character varying(30) NOT NULL,
    merchant_order_id character varying(80) NOT NULL,
    stella_payment_id character varying(120),
    receipt_url character varying(500),
    CONSTRAINT cash_charges_status_check CHECK (((status)::text = ANY ((ARRAY['READY'::character varying, 'PAID'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying])::text[])))
);

ALTER TABLE public.cash_charges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cash_charges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.cash_transactions (
    amount bigint NOT NULL,
    balance_after bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    type character varying(30) NOT NULL,
    ref_id character varying(120),
    memo character varying(300),
    CONSTRAINT cash_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['CHARGE'::character varying, 'SPEND'::character varying, 'REFUND'::character varying, 'ADJUSTMENT'::character varying])::text[])))
);

ALTER TABLE public.cash_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cash_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.categories (
    active boolean NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    name character varying(80) NOT NULL
);

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.contact_inquiries (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    category character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    title character varying(160) NOT NULL,
    attachment_url character varying(500),
    content oid NOT NULL,
    CONSTRAINT contact_inquiries_category_check CHECK (((category)::text = ANY ((ARRAY['PAYMENT'::character varying, 'ACCOUNT'::character varying, 'EVENT'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT contact_inquiries_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'ANSWERED'::character varying, 'CLOSED'::character varying])::text[])))
);

ALTER TABLE public.contact_inquiries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_inquiries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.contact_replies (
    admin_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    inquiry_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    content oid NOT NULL
);

ALTER TABLE public.contact_replies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_replies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.event_participations (
    claimed_at timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    event_id bigint NOT NULL,
    id bigint NOT NULL,
    outbound_mail_id bigint,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    claim_key character varying(80) NOT NULL
);

ALTER TABLE public.event_participations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_participations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.events (
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    end_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    mail_template_id bigint NOT NULL,
    start_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    type character varying(30) NOT NULL,
    name character varying(120) NOT NULL,
    description oid NOT NULL,
    CONSTRAINT events_type_check CHECK (((type)::text = ANY ((ARRAY['ATTENDANCE'::character varying, 'INVITE'::character varying, 'PAYBACK'::character varying, 'GENERAL'::character varying])::text[])))
);

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.mail_templates (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    mail_code character varying(80) NOT NULL,
    subject character varying(160) NOT NULL,
    content oid NOT NULL,
    rewards_json oid NOT NULL
);

ALTER TABLE public.mail_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mail_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.notices (
    pinned boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    title character varying(160) NOT NULL,
    content oid NOT NULL
);

ALTER TABLE public.notices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.outbound_mails (
    retry_count integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    next_retry_at timestamp(6) with time zone,
    sent_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    source_type character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    target_uuid character varying(36) NOT NULL,
    mail_code character varying(80) NOT NULL,
    source_ref_id character varying(120) NOT NULL,
    subject character varying(160) NOT NULL,
    idempotency_key character varying(180) NOT NULL,
    last_error character varying(500),
    content oid NOT NULL,
    rewards_json oid NOT NULL,
    CONSTRAINT outbound_mails_source_type_check CHECK (((source_type)::text = ANY ((ARRAY['EVENT'::character varying, 'PURCHASE'::character varying, 'ADMIN'::character varying, 'REDEEM_CODE'::character varying])::text[]))),
    CONSTRAINT outbound_mails_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SENT'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE public.outbound_mails ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outbound_mails_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.popups (
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    end_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    start_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    image_url character varying(500) NOT NULL,
    link_url character varying(500)
);

ALTER TABLE public.popups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.popups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.products (
    active boolean NOT NULL,
    new_badge boolean NOT NULL,
    recommended boolean NOT NULL,
    stock_quantity integer,
    category_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    mail_template_id bigint NOT NULL,
    price bigint NOT NULL,
    price_updated_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    name character varying(120) NOT NULL,
    image_url character varying(500),
    description oid NOT NULL
);

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.purchase_orders (
    quantity integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    outbound_mail_id bigint,
    product_id bigint NOT NULL,
    total_price bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    status character varying(30) NOT NULL,
    order_number character varying(80) NOT NULL,
    CONSTRAINT purchase_orders_status_check CHECK (((status)::text = ANY ((ARRAY['COMPLETED'::character varying, 'CANCELLED'::character varying, 'MAIL_PENDING'::character varying, 'MAIL_FAILED'::character varying])::text[])))
);

ALTER TABLE public.purchase_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.redeem_code_usages (
    code_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    outbound_mail_id bigint,
    updated_at timestamp(6) with time zone NOT NULL,
    used_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.redeem_code_usages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.redeem_code_usages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.redeem_codes (
    active boolean NOT NULL,
    max_uses integer NOT NULL,
    used_count integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone,
    id bigint NOT NULL,
    mail_template_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    code character varying(80) NOT NULL
);

ALTER TABLE public.redeem_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.redeem_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.refund_requests (
    cash_charge_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    processed_at timestamp(6) with time zone,
    processed_by bigint,
    updated_at timestamp(6) with time zone NOT NULL,
    status character varying(30) NOT NULL,
    operator_memo character varying(500),
    reason oid NOT NULL,
    CONSTRAINT refund_requests_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'COMPLETED'::character varying])::text[])))
);

ALTER TABLE public.refund_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refund_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.terms (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    published_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    type character varying(30) NOT NULL,
    version character varying(40) NOT NULL,
    content oid NOT NULL,
    CONSTRAINT terms_type_check CHECK (((type)::text = ANY ((ARRAY['TERMS'::character varying, 'PRIVACY'::character varying, 'REFUND'::character varying])::text[])))
);

ALTER TABLE public.terms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    marketing_agreed boolean,
    agreed_privacy_at timestamp(6) with time zone,
    agreed_terms_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    withdrawn_at timestamp(6) with time zone,
    role character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    minecraft_username character varying(32) NOT NULL,
    minecraft_uuid character varying(36) NOT NULL,
    microsoft_sub character varying(120) NOT NULL,
    email character varying(254),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'OPERATOR'::character varying, 'SUPER_ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'WITHDRAWN'::character varying])::text[])))
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT admin_users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cash_balances
    ADD CONSTRAINT cash_balances_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cash_balances
    ADD CONSTRAINT cash_balances_user_id_key UNIQUE (user_id);

ALTER TABLE ONLY public.cash_charges
    ADD CONSTRAINT cash_charges_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cash_transactions
    ADD CONSTRAINT cash_transactions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.contact_inquiries
    ADD CONSTRAINT contact_inquiries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.contact_replies
    ADD CONSTRAINT contact_replies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.event_participations
    ADD CONSTRAINT event_participations_outbound_mail_id_key UNIQUE (outbound_mail_id);

ALTER TABLE ONLY public.event_participations
    ADD CONSTRAINT event_participations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mail_templates
    ADD CONSTRAINT mail_templates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notices
    ADD CONSTRAINT notices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.outbound_mails
    ADD CONSTRAINT outbound_mails_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.popups
    ADD CONSTRAINT popups_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT purchase_orders_outbound_mail_id_key UNIQUE (outbound_mail_id);

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT purchase_orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.redeem_code_usages
    ADD CONSTRAINT redeem_code_usages_outbound_mail_id_key UNIQUE (outbound_mail_id);

ALTER TABLE ONLY public.redeem_code_usages
    ADD CONSTRAINT redeem_code_usages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.redeem_codes
    ADD CONSTRAINT redeem_codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.refund_requests
    ADD CONSTRAINT refund_requests_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.terms
    ADD CONSTRAINT terms_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT uk_admin_users_username UNIQUE (username);

ALTER TABLE ONLY public.cash_charges
    ADD CONSTRAINT uk_cash_charges_order_id UNIQUE (merchant_order_id);

ALTER TABLE ONLY public.cash_charges
    ADD CONSTRAINT uk_cash_charges_stella_payment UNIQUE (stella_payment_id);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT uk_categories_name UNIQUE (name);

ALTER TABLE ONLY public.event_participations
    ADD CONSTRAINT uk_event_participations_once UNIQUE (user_id, event_id, claim_key);

ALTER TABLE ONLY public.mail_templates
    ADD CONSTRAINT uk_mail_templates_code UNIQUE (mail_code);

ALTER TABLE ONLY public.outbound_mails
    ADD CONSTRAINT uk_outbound_mails_idempotency UNIQUE (idempotency_key);

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT uk_purchase_orders_order_number UNIQUE (order_number);

ALTER TABLE ONLY public.redeem_code_usages
    ADD CONSTRAINT uk_redeem_code_usages_once UNIQUE (code_id, user_id);

ALTER TABLE ONLY public.redeem_codes
    ADD CONSTRAINT uk_redeem_codes_code UNIQUE (code);

ALTER TABLE ONLY public.terms
    ADD CONSTRAINT uk_terms_type_version UNIQUE (type, version);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_microsoft_sub UNIQUE (microsoft_sub);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_minecraft_uuid UNIQUE (minecraft_uuid);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

CREATE INDEX idx_audit_logs_actor_created ON public.audit_logs USING btree (actor, created_at);

CREATE INDEX idx_audit_logs_entity ON public.audit_logs USING btree (entity_type, entity_id);

CREATE INDEX idx_cash_charges_user_created ON public.cash_charges USING btree (user_id, created_at);

CREATE INDEX idx_cash_transactions_user_created ON public.cash_transactions USING btree (user_id, created_at);

CREATE INDEX idx_contact_inquiries_user_created ON public.contact_inquiries USING btree (user_id, created_at);

CREATE INDEX idx_event_participations_user ON public.event_participations USING btree (user_id);

CREATE INDEX idx_events_active_period ON public.events USING btree (active, start_at, end_at);

CREATE INDEX idx_notices_pinned_created ON public.notices USING btree (pinned, created_at);

CREATE INDEX idx_outbound_mails_status_created ON public.outbound_mails USING btree (status, created_at);

CREATE INDEX idx_outbound_mails_target ON public.outbound_mails USING btree (target_uuid);

CREATE INDEX idx_popups_active_period ON public.popups USING btree (active, start_at, end_at);

CREATE INDEX idx_products_category_active ON public.products USING btree (category_id, active);

CREATE INDEX idx_products_price ON public.products USING btree (price);

CREATE INDEX idx_purchase_orders_user_created ON public.purchase_orders USING btree (user_id, created_at);

CREATE INDEX idx_redeem_code_usages_user ON public.redeem_code_usages USING btree (user_id);

CREATE INDEX idx_redeem_codes_active ON public.redeem_codes USING btree (active, expires_at);

CREATE INDEX idx_terms_type_published ON public.terms USING btree (type, published_at);

CREATE INDEX idx_users_minecraft_username ON public.users USING btree (minecraft_username);

CREATE INDEX idx_users_status ON public.users USING btree (status);

ALTER TABLE ONLY public.contact_replies
    ADD CONSTRAINT fk2r39h6x99prir3mna3n13ty71 FOREIGN KEY (admin_id) REFERENCES public.admin_users(id);

ALTER TABLE ONLY public.event_participations
    ADD CONSTRAINT fk4oi2ae8wq2rygr2uei24wa69m FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.cash_transactions
    ADD CONSTRAINT fk4qfnaw1qiigfc332jltxgvj4r FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT fk71uolhj6hix35a4narqgbifi4 FOREIGN KEY (outbound_mail_id) REFERENCES public.outbound_mails(id);

ALTER TABLE ONLY public.event_participations
    ADD CONSTRAINT fk82r3maaey0bvtw2y1bydrfmkd FOREIGN KEY (outbound_mail_id) REFERENCES public.outbound_mails(id);

ALTER TABLE ONLY public.redeem_code_usages
    ADD CONSTRAINT fk8yacffkr8jms5gr12uob44d7j FOREIGN KEY (code_id) REFERENCES public.redeem_codes(id);

ALTER TABLE ONLY public.redeem_codes
    ADD CONSTRAINT fkcc0ymobjffbhxid164p1494kn FOREIGN KEY (mail_template_id) REFERENCES public.mail_templates(id);

ALTER TABLE ONLY public.redeem_code_usages
    ADD CONSTRAINT fkcq6ob39x5256cwu13nj5x67b7 FOREIGN KEY (outbound_mail_id) REFERENCES public.outbound_mails(id);

ALTER TABLE ONLY public.contact_replies
    ADD CONSTRAINT fkfrhpdawr8htoa87lwkd4id8jh FOREIGN KEY (inquiry_id) REFERENCES public.contact_inquiries(id);

ALTER TABLE ONLY public.cash_balances
    ADD CONSTRAINT fkfxjlcxoc1o5rciksgprfmax86 FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.events
    ADD CONSTRAINT fkgmptspcfccx3q1asddc9bqou5 FOREIGN KEY (mail_template_id) REFERENCES public.mail_templates(id);

ALTER TABLE ONLY public.cash_charges
    ADD CONSTRAINT fkh0txkaxqms37dte973tx7l2kr FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT fkh6winackew5b8ljk4se6f8hrg FOREIGN KEY (product_id) REFERENCES public.products(id);

ALTER TABLE ONLY public.refund_requests
    ADD CONSTRAINT fkilerkka4jbcmaxcr9r1fh55l FOREIGN KEY (cash_charge_id) REFERENCES public.cash_charges(id);

ALTER TABLE ONLY public.contact_inquiries
    ADD CONSTRAINT fkj66ubi79t20jeis7pof6fvci0 FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.refund_requests
    ADD CONSTRAINT fkjhyny425olgqb0npqiilsxfvw FOREIGN KEY (processed_by) REFERENCES public.admin_users(id);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);

ALTER TABLE ONLY public.event_participations
    ADD CONSTRAINT fkop8sidel0e8jhh44ihbtulm17 FOREIGN KEY (event_id) REFERENCES public.events(id);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkpa7eufmdxkv72vyq1ir5paly3 FOREIGN KEY (mail_template_id) REFERENCES public.mail_templates(id);

ALTER TABLE ONLY public.redeem_code_usages
    ADD CONSTRAINT fkq5vffupjpl8sj7jqufvosqsi5 FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT fkquq1njrq27p9ye5u19f1yvnfp FOREIGN KEY (user_id) REFERENCES public.users(id);

