-- 유저 경고 부여/취소 기록 (07-09 피드백: 경고 시스템).
CREATE TABLE public.warnings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users (id),
    reason character varying(30) NOT NULL,
    detail text NOT NULL,
    custom_text character varying(500),
    count_at_issue integer NOT NULL,
    issued_by character varying(80),
    canceled boolean NOT NULL DEFAULT false,
    canceled_reason character varying(300),
    canceled_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT warnings_reason_check CHECK (((reason)::text = ANY ((ARRAY[
        'MISCONDUCT'::character varying,
        'BUG_ABUSE'::character varying,
        'CUSTOM'::character varying
    ])::text[])))
);

CREATE INDEX idx_warnings_user_created ON public.warnings USING btree (user_id, created_at);
